modLoader="javafml" #mandatory
loaderVersion="[24,)" #mandatory (24 is current forge version)
issueTrackerURL="http://github.com/ben_mkiv/foreveryoung/issues" #optional
displayURL="https://minecraft.curseforge.com/projects/foreveryoung" #optional
#logoFile="foreveryoung.png" #optional
credits="ben_mkiv (code), luni (for the inspiration to create this mod)" #optional
authors="ben_mkiv" #optional
[[mods]] #mandatory
modId="foreveryoung" #mandatory
version="${file.jarVersion}" #mandatory
displayName="ForeverYoung" #mandatory
#updateJSONURL="" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Mod that allows you to extend the timespan a mob will stay a baby before growing up'''